---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: atomic-fedora
description: This is my personal OS image

base-image: ghcr.io/ublue-os/bazzite-dx-nvidia
image-version: stable

modules:

  # general packages
  - type: script
    snippets:
      - "dnf5 install -y vlc konsole okular rust cargo dbus-devel"

  # firefox
  - type: script
    snippets:
      - "dnf5 config-manager setopt fedora-cisco-openh264.enabled=1"
      - "dnf5 install -y firefox --allowerasing"

  # vscode
  - type: dnf
    remove:
      packages:
        - code

  # first time installer
  - type: script
    snippets:
      - "cp /tmp/files/post-install-checker/post-install-checker.service /usr/lib/systemd/user/"
      - "systemctl --global enable post-install-checker.service"

  # sublime-text
  - type: script
    snippets:
      - "rpm -v --import https://download.sublimetext.com/sublimehq-rpm-pub.gpg"
      - "dnf5 config-manager addrepo --from-repofile=https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo"
      - "dnf5 makecache"
      - "dnf5 install -y sublime-text"

  # google chrome
  - type: script
    snippets:
      - "dnf5 install -y fedora-workstation-repositories"
      - "dnf5 config-manager setopt google-chrome.enabled=1"
      - "dnf5 install -y google-chrome-stable"

  # klassy 
  - type: script
    snippets:
      - "dnf config-manager addrepo --from-repofile=https://download.opensuse.org/repositories/home:paul4us/Fedora_43/home:paul4us.repo"
      - "dnf5 makecache"
      - "dnf5 install -y klassy"

  # 1password
  - type: script
    scripts:
      - install-1password.sh

  # slack
  - type: script
    scripts:
      - install-slack.sh

  # teams
  - type: script
    scripts:
      - install-teams.sh

  # fix gtk borders
  - type: script
    snippets:
      - "dnf5 copr enable -y hdfssk/gtk3-nocsd"
      - "dnf5 install -y gtk3-nocsd"

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
