---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: atomic-fedora
description: This is my personal OS image

base-image: ghcr.io/ublue-os/bazzite-dx-nvidia
image-version: stable

modules:

  # steam configs
  - type: files
    files:
      - source: steam-fixer/script.sh
        destination: /usr/bin/steam-fixer.sh
      - source: steam-fixer/systemd.service
        destination: /usr/lib/systemd/user/steam-fixer.service

  # firefox
  - type: script
    snippets:
      - "dnf5 config-manager setopt fedora-cisco-openh264.enabled=1"
      - "dnf5 install -y firefox --allowerasing"

  # vscode
  - type: dnf
    remove:
      packages:
        - code

  # first time installer
  - type: files
    files:
      - source: first-time-checker/trigger.sh
        destination: /etc/profile.d/first-time-checker.sh
      - source: first-time-checker/entry.desktop
        destination: /usr/share/first-time-checker.desktop
      - source: first-time-checker/script
        destination: /usr/bin/first-time-checker
  - type: script
    snippets:
      - "chmod 755 /usr/bin/first-time-checker"

  # sublime-text
  - type: script
    snippets:
      - "rpm -v --import https://download.sublimetext.com/sublimehq-rpm-pub.gpg"
      - "dnf5 config-manager addrepo --from-repofile=https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo"
      - "dnf5 makecache"
      - "dnf5 install -y sublime-text"

  # google chrome
  - type: script
    snippets:
      - "dnf5 install -y fedora-workstation-repositories"
      - "dnf5 config-manager setopt google-chrome.enabled=1"
      - "dnf5 install -y google-chrome-stable"

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
