---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: atomic-fedora
description: This is my personal OS image

base-image: ghcr.io/ublue-os/bazzite-dx-nvidia-gnome
image-version: stable

modules:

  # steam configs
  - type: files
    files:
      - source: steam-fixer/script.sh
        destination: /usr/bin/steam-fixer.sh
      - source: steam-fixer/systemd.service
        destination: /usr/lib/systemd/user/steam-fixer.service

  # obsidian
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: user
        install:
          - md.obsidian.Obsidian

  # firefox
  - type: script
    snippets:
      - "dnf5 config-manager setopt fedora-cisco-openh264.enabled=1"
      - "dnf5 install -y firefox --allowerasing"

  # first time installer
  - type: files
    files:
      - source: first-time-checker/trigger.sh
        destination: /etc/profile.d/first-time-checker.sh
      - source: first-time-checker/entry.desktop
        destination: /usr/share/first-time-checker.desktop
      - source: first-time-checker/script
        destination: /usr/bin/first-time-checker
  - type: script
    snippets:
      - "chmod 755 /usr/bin/first-time-checker"

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
