---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: atomic-fedora
description: This is my personal OS image

base-image: ghcr.io/ublue-os/bluefin-nvidia-open
image-version: 43

modules:

  # general packages
  - type: script
    snippets:
      - "dnf5 install -y vlc konsole okular rust cargo dbus-devel"

  # cosmic-desktop
  - type: script
    scripts:
      - install-cosmic-desktop.sh

  # firefox
  - type: script
    snippets:
      - "dnf5 config-manager setopt fedora-cisco-openh264.enabled=1"
      - "dnf5 install -y firefox --allowerasing"

  # vscode
  - type: dnf
    remove:
      packages:
        - code

  # first time installer
  - type: files
    files:
     - source: post-install-checker/post-install-checker.service
       destination: /usr/lib/systemd/user/post-install-checker.service
  - type: script
    snippets:
      - "systemctl --global enable post-install-checker.service"

  # sublime-text
  - type: script
    snippets:
      - "rpm -v --import https://download.sublimetext.com/sublimehq-rpm-pub.gpg"
      - "dnf5 config-manager addrepo --from-repofile=https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo"
      - "dnf5 makecache"
      - "dnf5 install -y sublime-text"

  # google chrome
  - type: script
    snippets:
      - "dnf5 install -y fedora-workstation-repositories"
      - "dnf5 config-manager setopt google-chrome.enabled=1"
      - "dnf5 install -y google-chrome-stable"

  # 1password
  - type: script
    scripts:
      - install-1password.sh

  # slack
  - type: script
    scripts:
      - install-slack.sh

  # teams
  - type: script
    scripts:
      - install-teams.sh

  # Steam
  - type: script
    scripts:
      - install-steam.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
