---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: atomic-fedora
description: This is my personal OS image

base-image: ghcr.io/ublue-os/bluefin-dx-nvidia-open
image-version: 43

modules:

  # all dnf packages to install
  - type: script
    scripts:
      - install-dnf-packages.sh

  # custom ujust tasks
  - type: files
    files:
     - source: ujust/60-custom.just
       destination: /usr/share/ublue-os/just/60-custom.just

  # script that runs on every login
  - type: files
    files:
     - source: post-install-checker/post-install-checker.service
       destination: /usr/lib/systemd/user/post-install-checker.service
  - type: script
    snippets:
      - "systemctl --global enable post-install-checker.service"

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
