---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: atomic-fedora
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bazzite-dx-nvidia-gnome
image-version: stable

modules:

  - type: files
    files:
      - source: scripts/steam-fixer.sh
        destination: /usr/bin/steam-fixer.sh
      - source: systemd/user/steam-fixer.service
        destination: /usr/lib/systemd/user/steam-fixer.service

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: user
        install:
          - md.obsidian.Obsidian

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
