#!/bin/sh

if test -e "$HOME"/.config/ublue/setup-done; then
  kdialog --title "first-time-checker" --passivepopup "This process has been already run" 10
  echo "first time checker has been run"
  exit 0
else
  kdialog --title "first-time-checker" --passivepopup "Starting first-time-checker script" 10
  echo "Starting first-time-checker script"
fi

##############################################################################################
##############################################################################################

# flapaks
kdialog --title "first-time-checker" --passivepopup "configuring flatpaks" 10
flatpak uninstall --delete-data org.mozilla.firefox -y
flatpak install -y md.obsidian.Obsidian

# steam
sed -i '/^\[Desktop Entry\]/a Hidden=true' "$HOME"/.config/autostart/steam.desktop

##############################################################################################
##############################################################################################

kdialog --title "first-time-checker" --passivepopup "Finishing first-time-checker script" 10
echo "Finishing first-time-checker script"

mkdir -p "$HOME"/.config/ublue/
touch "$HOME"/.config/ublue/setup-done

rm -f "$HOME"/.config/autostart/first-time-checker.desktop
